### PR TITLE
Feature/toggle admin view

### PR DESCRIPTION
**Pull request by danfunk**
fixes #219 - adds a preference service to the front end that will allow us to tweak system wide preferences for the front end.

### CODE REVIEW

**Comment by NWalker4483** [comment]
Some of the tests are failing so I'm going to delete node_modules and try again. In the future tho run `ng lint --fix` to automate fixing quote marks, trailing whitespace, etc

**Review by NWalker4483 — APPROVED** [review]

**Comment by danfunk** [comment]
ng lint --fix sounds downright delightful.  thank you for that.
The linting and tests all worked for me locally.  But that just doesn't
mean much these days does it?

**Comment by NWalker4483** [comment]
It might just be a Mac specific issue wouldn't be the first time. Which node/npm versions are you using?

**Comment by NWalker4483** [comment]
The lint runs fine and I can test the button in the frontend without issue so as long as the other test are passing on your machine I'm willing to push it. And figure out my issues separately

**Pull request merged**
